### ISSUE TITLE
Music Collection Indexing

### ISSUE THREAD

**Issue by symbiogenesis** [f35f22fan/Quince#1]
I assume a significant portion of the CPU usage from each player is from indexing. You should run a full suite of benchmarks with each competing player, with both indexing turned on and off.

Elisa seems interesting, since it uses baloo, which you'll already be using if you're a normal KDE user. I would like to see what Elisa's benchmarks are.

https://www.phoronix.com/scan.php?page=news_item&px=KDE-Elisa-Music-Player

**Comment by f35f22fan** [comment]
I'm not using any indexing and I think Clementine doesn't, at least note the way I use it (drag and drop files onto Clementine's playlist and click "play"). I just checked again, when Clementine plays a song and I hit pause, the CPU usage drops to 0% and stays there, when hitting "play" - if the window is visible: ~10% CPU, when hidden to sys tray - 5% CPU. So in this case the CPU usage stems from how often, how efficient and what is the player redrawing on its window surface (e.g. if you have a visible equalizer that's a lot of extra redrawing calls per second), the 2nd reason could be how efficient is its audio backend.

And I'm pretty sure I won't do indexing of music files despite some people using/liking it, but I turn off any kind of indexing when I install Linux, quite frankly I hate anyone doing files indexing in the background. I think indexing can be mostly replaced with other methods consuming no or much less CPU. I'm developing a classic pragmatic audio player like Winamp used to be once, of course with extra features that I'll find worth developing, including ones for music classification.
